name: Update

on:
  push:
    paths:
      - '.github/workflows/update.yml'
  
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Top 1M List
        run: |
          wget https://s3.amazonaws.com/alexa-static/top-1m.csv.zip
          unzip top-1m.csv.zip

      - name: Create TXTs
        run: |
          mkdir -p txt
          awk -F ',' '{print $2}' top-1m.csv|cat > txt/1m.txt
          awk -F ',' '{print $2}' top-1m.csv|head -100000 > txt/100000.txt
          awk -F ',' '{print $2}' top-1m.csv|head -10000 > txt/10000.txt
          awk -F ',' '{print $2}' top-1m.csv|head -1000 > txt/1000.txt
          awk -F ',' '{print $2}' top-1m.csv|head -100 > txt/100.txt

      - name: Create CSVs
        run: |
          mkdir -p csv
          cp top-1m.csv csv/1m.csv
          head -100000 top-1m.csv > csv/100000.csv
          head -10000 top-1m.csv > csv/10000.csv
          head -1000 top-1m.csv > csv/1000.csv
          head -100 top-1m.csv > csv/100.csv

      - name: Miscellaneous
        run: |
          rm top-1m.csv*
          echo `date +%s` > last-updated.txt

      - name: Push to GitHub 
        run: |
          git config user.name lonelil
          git config user.email 51315646+lonelil@users.noreply.github.com
          git add .
          git commit -m "Update ($(date +'%Y-%m-%dT%H:%M:%S'))"
          git push

